import { fileURLToPath } from "node:url";
import { and, asc, desc, eq, gte, lt, sql, type SQL } from "drizzle-orm";
import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import pg from "pg";
import * as schema from "./schema.js";
import type { AuditContext, AuditEntry, ListFilter, Transaction, TransactionPatch, TransactionStore } from "./types.js";

type Db = PgDatabase<PgQueryResultHKT, typeof schema>;
type Row = typeof schema.transactions.$inferSelect;
type Insert = typeof schema.transactions.$inferInsert;

/** Folder holding the committed SQL migrations generated by drizzle-kit. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../../drizzle", import.meta.url));

/**
 * Durable `TransactionStore` on PostgreSQL via Drizzle ORM. Works with any
 * Drizzle Postgres driver: `node-postgres` in production, PGlite in tests.
 */
export class PostgresTransactionStore implements TransactionStore {
  constructor(
    private readonly db: Db,
    private readonly onClose: () => Promise<void> = async () => {},
  ) {}

  /** Connects with `node-postgres` and applies pending migrations. */
  static async connect(databaseUrl: string): Promise<PostgresTransactionStore> {
    const pool = new pg.Pool({ connectionString: databaseUrl, max: 10 });
    const db: NodePgDatabase<typeof schema> = drizzle(pool, { schema });
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    return new PostgresTransactionStore(db, () => pool.end());
  }

  async create(input: Omit<Transaction, "startedAt" | "updatedAt">, audit?: AuditContext): Promise<Transaction> {
    const now = new Date();
    const row = toRow({ ...input, startedAt: now, updatedAt: now });
    return this.db.transaction(async (tx) => {
      const [inserted] = await tx.insert(schema.transactions).values(row).returning();
      await tx.insert(schema.auditLog).values({
        transactionId: input.id,
        fromStatus: null,
        toStatus: input.status,
        actor: audit?.actor ?? "system",
        note: audit?.note ?? null,
        at: now,
      });
      return fromRow(inserted!);
    });
  }

  async get(id: string): Promise<Transaction | undefined> {
    const [row] = await this.db.select().from(schema.transactions).where(eq(schema.transactions.id, id));
    return row ? fromRow(row) : undefined;
  }

  async findByWithdrawMemo(memo: string): Promise<Transaction | undefined> {
    const [row] = await this.db
      .select()
      .from(schema.transactions)
      .where(and(eq(schema.transactions.withdrawMemo, memo), eq(schema.transactions.kind, "withdrawal")));
    return row ? fromRow(row) : undefined;
  }

  async findByEscrowTxId(txIdHex: string): Promise<Transaction | undefined> {
    const [row] = await this.db
      .select()
      .from(schema.transactions)
      .where(eq(schema.transactions.escrowTxId, txIdHex.toLowerCase()));
    return row ? fromRow(row) : undefined;
  }

  async update(id: string, patch: TransactionPatch, audit?: AuditContext): Promise<Transaction> {
    return this.db.transaction(async (tx) => {
      // Lock the row so concurrent watchers can't interleave transitions.
      const [current] = await tx.select().from(schema.transactions).where(eq(schema.transactions.id, id)).for("update");
      if (!current) throw new Error(`Transaction ${id} not found`);

      const now = new Date();
      const merged = { ...fromRow(current), ...patch, updatedAt: now };
      const [updated] = await tx
        .update(schema.transactions)
        .set(toRow(merged))
        .where(eq(schema.transactions.id, id))
        .returning();

      if (patch.status && patch.status !== current.status) {
        await tx.insert(schema.auditLog).values({
          transactionId: id,
          fromStatus: current.status,
          toStatus: patch.status,
          actor: audit?.actor ?? "system",
          note: audit?.note ?? null,
          at: now,
        });
      }
      return fromRow(updated!);
    });
  }

  async list(filter: ListFilter): Promise<Transaction[]> {
    const t = schema.transactions;
    const conditions: SQL[] = [eq(t.account, filter.account)];
    if (filter.assetCode) conditions.push(eq(t.assetCode, filter.assetCode));
    if (filter.kind) conditions.push(eq(t.kind, filter.kind));
    if (filter.noOlderThan) conditions.push(gte(t.startedAt, filter.noOlderThan));
    if (filter.pagingId) {
      const anchor = await this.get(filter.pagingId);
      if (anchor) conditions.push(lt(t.startedAt, anchor.startedAt));
    }
    const rows = await this.db
      .select()
      .from(t)
      .where(and(...conditions))
      .orderBy(desc(t.startedAt))
      .limit(filter.limit ?? 100);
    return rows.map(fromRow);
  }

  async auditLog(transactionId: string): Promise<AuditEntry[]> {
    const rows = await this.db
      .select()
      .from(schema.auditLog)
      .where(eq(schema.auditLog.transactionId, transactionId))
      .orderBy(asc(schema.auditLog.id));
    return rows.map((r) => ({
      transactionId: r.transactionId,
      fromStatus: r.fromStatus,
      toStatus: r.toStatus,
      actor: r.actor,
      note: r.note ?? undefined,
      at: r.at,
    }));
  }

  async getCursor(name: string): Promise<string | undefined> {
    const [row] = await this.db.select().from(schema.cursors).where(eq(schema.cursors.name, name));
    return row?.value;
  }

  async setCursor(name: string, value: string): Promise<void> {
    await this.db
      .insert(schema.cursors)
      .values({ name, value, updatedAt: new Date() })
      .onConflictDoUpdate({ target: schema.cursors.name, set: { value, updatedAt: new Date() } });
  }

  async recordWebhookEvent(provider: string, eventId: string): Promise<boolean> {
    const inserted = await this.db
      .insert(schema.webhookEvents)
      .values({ provider, eventId })
      .onConflictDoNothing()
      .returning({ eventId: schema.webhookEvents.eventId });
    return inserted.length > 0;
  }

  async forgetWebhookEvent(provider: string, eventId: string): Promise<void> {
    await this.db
      .delete(schema.webhookEvents)
      .where(and(eq(schema.webhookEvents.provider, provider), eq(schema.webhookEvents.eventId, eventId)));
  }

  async ping(): Promise<void> {
    await this.db.execute(sql`select 1`);
  }

  async close(): Promise<void> {
    await this.onClose();
  }
}

function toRow(tx: Transaction): Insert {
  return {
    id: tx.id,
    kind: tx.kind,
    status: tx.status,
    account: tx.account,
    accountMemo: tx.accountMemo ?? null,
    clientDomain: tx.clientDomain ?? null,
    assetCode: tx.assetCode,
    assetIssuer: tx.assetIssuer,
    amountIn: tx.amountIn ?? null,
    amountOut: tx.amountOut ?? null,
    amountFee: tx.amountFee ?? null,
    to: tx.to ?? null,
    from: tx.from ?? null,
    withdrawAnchorAccount: tx.withdrawAnchorAccount ?? null,
    withdrawMemo: tx.withdrawMemo ?? null,
    withdrawMode: tx.withdrawMode ?? null,
    escrowTxId: tx.escrow?.txId ?? null,
    escrow: tx.escrow ?? null,
    depositInstructions: tx.depositInstructions ?? null,
    stellarTransactionId: tx.stellarTransactionId ?? null,
    externalTransactionId: tx.externalTransactionId ?? null,
    message: tx.message ?? null,
    refunds: tx.refunds ?? null,
    onChangeCallback: tx.onChangeCallback ?? null,
    lang: tx.lang ?? null,
    customer: tx.customer ?? null,
    startedAt: tx.startedAt,
    updatedAt: tx.updatedAt,
    completedAt: tx.completedAt ?? null,
  };
}

function fromRow(row: Row): Transaction {
  const tx: Transaction = {
    id: row.id,
    kind: row.kind,
    status: row.status,
    account: row.account,
    assetCode: row.assetCode,
    assetIssuer: row.assetIssuer,
    startedAt: row.startedAt,
    updatedAt: row.updatedAt,
  };
  // Map SQL NULL to "absent" so both stores return identical objects.
  const optional = {
    accountMemo: row.accountMemo,
    clientDomain: row.clientDomain,
    amountIn: row.amountIn,
    amountOut: row.amountOut,
    amountFee: row.amountFee,
    to: row.to,
    from: row.from,
    withdrawAnchorAccount: row.withdrawAnchorAccount,
    withdrawMemo: row.withdrawMemo,
    withdrawMode: row.withdrawMode,
    escrow: row.escrow,
    depositInstructions: row.depositInstructions,
    stellarTransactionId: row.stellarTransactionId,
    externalTransactionId: row.externalTransactionId,
    message: row.message,
    refunds: row.refunds,
    onChangeCallback: row.onChangeCallback,
    lang: row.lang,
    customer: row.customer,
    completedAt: row.completedAt,
  };
  for (const [key, value] of Object.entries(optional)) {
    if (value !== null && value !== undefined) (tx as unknown as Record<string, unknown>)[key] = value;
  }
  return tx;
}
